In [16]:
import pandas as pd

In [ ]:
df = pd.DataFrame(
    {
        'Turmas': [315, 319, 419, 713, 718],
        'Módulos': ['Python', 'Python', 'Python', 'Python', 'Python'],
        'Horário de Início': ['15:30', '19:00', '19:00', '13:30', '18:30']
    }
)

df

   Turmas Módulos Horário de Início
0     315  Python             15:30
1     319  Python             19:00
2     419  Python             19:00
3     713  Python             13:30
4     718  Python             18:30

In [ ]:
# get_loc -> Método específico para visualizar a posição
df.set_index('Turmas', inplace=True)
df

       Módulos Horário de Início
Turmas
315     Python             15:30
319     Python             19:00
419     Python             19:00
713     Python             13:30
718     Python             18:30

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df

   Turmas Módulos Horário de Início
0     315  Python             15:30
1     319  Python             19:00
2     419  Python             19:00
3     713  Python             13:30
4     718  Python             18:30

In [ ]:
df

                   Turmas Módulos
Horário de Início
15:30                 315  Python
19:00                 319  Python
19:00                 419  Python
13:30                 713  Python
18:30                 718  Python

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df

   index Horário de Início  Turmas Módulos
0      0             15:30     315  Python
1      1             19:00     319  Python
2      2             19:00     419  Python
3      3             13:30     713  Python
4      4             18:30     718  Python

In [14]:
dataset = r'https://raw.githubusercontent.com/rafaelpuyau/infinity_school/main/ds/datasets/atividade_casa.csv'

In [17]:
df = pd.read_csv(dataset)

In [18]:
df['Valor'] > 100

0        False
1        False
2        False
3         True
4         True
         ...
99995     True
99996     True
99997    False
99998     True
99999     True
Name: Valor, Length: 100000, dtype: bool

In [22]:
# Primeira Pergunta
maior_100 = df['Valor'] > 100
df.loc[maior_100].count()

Produto          61856
Cor              61856
Valor            61856
Quantidade       61856
Sexo             61856
Idade            61856
Data da Venda    61856
Canal            61856
dtype: int64

In [21]:
# Segunda pergunta
funcao1 = (df['Produto'] == 'Saia')
funcao2 = (df['Valor'] < 70)

saias = df.loc[(funcao1 & funcao2)]
saias['Quantidade'].sum()

7635

In [23]:
df

,Produto,Cor,Valor,Quantidade,Sexo,Idade,Data da Venda,Canal
0,Calça,Roxa,66.947509,4,Masculino,39,2022-02-25,Loja Virtual
1,Camiseta,Amarela,99.692292,1,Masculino,30,2022-01-19,Loja Física
2,Calça,Azul,92.502413,2,Feminino,25,2022-03-11,Loja Física
3,Short,Azul,162.693470,1,Feminino,45,2022-05-01,Loja Física
4,Camiseta,Laranja,148.191049,3,Feminino,29,2022-03-13,Loja Física
...,...,...,...,...,...,...,...,...
99995,Calça,Laranja,101.158897,4,Masculino,46,2022-01-24,Loja Física
99996,Saia,Preta,100.815311,3,Masculino,28,2022-03-08,Loja Física
99997,Calça,Azul,63.924217,4,Feminino,48,2022-06-08,Loja Virtual
99998,Calça,Azul,149.062392,3,Feminino,19,2022-01-05,Loja Física
99999,Saia,Verde,114.089710,3,Masculino,25,2022-04-19,Loja Virtual

In [30]:
camisa_laranja = df.loc[(df['Produto'] == 'Camiseta') & (df['Cor'] == 'Laranja')]

In [34]:
calculo = camisa_laranja['Valor'] * camisa_laranja['Quantidade']

In [37]:
camisa_laranja.insert(4, 'Total', calculo)

In [39]:
camisa_laranja['Total'].sum()

726700.8485076721

In [41]:
calca = df['Produto'] == 'Calça'
cor = df['Cor'] == 'Roxa'
q4 = df[calca & cor]

In [42]:
q4.loc[
    (df['Idade'] >= 30)
    &
    (df['Idade'] <= 40)
]

,Produto,Cor,Valor,Quantidade,Sexo,Idade,Data da Venda,Canal
0,Calça,Roxa,66.947509,4,Masculino,39,2022-02-25,Loja Virtual
154,Calça,Roxa,137.384350,4,Masculino,40,2022-06-03,Loja Virtual
245,Calça,Roxa,154.232319,1,Feminino,35,2022-07-18,Loja Virtual
331,Calça,Roxa,75.355112,2,Masculino,35,2022-02-06,Loja Virtual
502,Calça,Roxa,127.690324,2,Feminino,34,2022-05-02,Loja Virtual
...,...,...,...,...,...,...,...,...
99579,Calça,Roxa,102.778921,4,Feminino,30,2022-05-26,Loja Física
99610,Calça,Roxa,139.569987,1,Masculino,36,2022-06-07,Loja Virtual
99745,Calça,Roxa,72.606873,2,Feminino,40,2022-05-08,Loja Física
99826,Calça,Roxa,103.181621,3,Feminino,37,2022-07-10,Loja Virtual
99971,Calça,Roxa,120.525544,4,Masculino,31,2022-02-22,Loja Virtual