In [2]:
import pandas as pd

In [3]:
dataset = r'https://raw.githubusercontent.com/rafaelpuyau/infinity_school/main/ds/datasets/wines.csv'
df = pd.read_csv(dataset)

In [4]:
df.sample(5)

            date   label  vintage   style    country   price  quantity  rate
4523  2021-01-06  Wine J     1987     Red  Argentina  270.92         8    80
3764  2021-06-16  Wine A     2000     Red  Argentina  191.78        11    84
5354  2021-05-18  Wine Y     2014  Orange      Italy  186.25        15    85
9772  2021-11-10  Wine Y     1984  Orange        USA  383.01         7    81
4358  2021-11-04  Wine W     1984   Sweet  Argentina  118.85         4    98

# Questão 1

###Quanto custa o vinho mais caro

In [15]:
vinho_mais_caro = df['price'].max()
print(f'O vinho mais caro custa: {vinho_mais_caro}')

O vinho mais caro custa: 1107.89

#Questão 2
###Vinho mais barato

In [16]:
vinho_mais_barato = df['price'].min()
print(f'O vinho mais barato custa: {vinho_mais_barato}')

O vinho mais barato custa: 50.01

#Questão 3
### Qual o vinho mais caro

In [47]:
nome_vinho_mais_caro = df.loc[(df['label'] == 'Wine Q') & (df['price'] == vinho_mais_caro)]
print(f'O vinho mais caro é: {nome_vinho_mais_caro["label"].to_frame()}')

O vinho mais caro é:        label
1249  Wine Q

#Questão 4
### Vinho mais barato

In [49]:
# Wine Z
nome_vinho_mais_barato = df.loc[(df['label'] == 'Wine Z') & (df['price'] == vinho_mais_barato)]
print(f"O vinho mais barato é: {nome_vinho_mais_barato['label'].to_frame()}")

O vinho mais barato é:        label
4910  Wine Z

#Questão 5
### Quanto foi vendido em 2021

In [55]:
df['date'] = pd.to_datetime(df['date'])
df.dtypes

date        datetime64[ns]
label               object
vintage              int64
style               object
country             object
price              float64
quantity             int64
rate                 int64
dtype: object

In [58]:
quantidade_total = df['quantity'].sum()
print(f'A quantaidade total vendida foi {quantidade_total}')

A quantaidade total vendida foi 80155

#Questão 6
###Quantas garrafas no total

In [62]:
quantidade_garrafas = len(df.index)
print(f'A quantidade de garrafas é de: {quantidade_garrafas}')

A quantidade de garrafas é de: 10000

#Questão 7
### Qual vinho teve a maior nota

In [63]:
maior_nota = df['rate'].max()
print(f'A maior nota foi de: {maior_nota}')

100

#Questão 8
###Menor nota

In [65]:
menor_nota = df['rate'].min()
print(f'A maior nota foi de: {menor_nota}')

A maior nota foi de: 75

#Questão 9
### Qual a safra mais antiga

In [66]:
safra_antiga = df['vintage'].min()
print(f"A safra mais antiga é {safra_antiga}")

A safra mais antiga é 1982

#Questão 10
### A safra mais recente

In [67]:
safra_recente = df['vintage'].max()
print(f"A safra mais antiga é {safra_recente}")

A safra mais antiga é 2021

#Questão 11
###Qual país teve a garrafa menos vendida

In [72]:
paises = df.groupby('country')['quantity'].sum()

In [91]:
paises.sort_values().to_frame().reset_index()[:1]

  country  quantity
0     USA      7402

In [87]:
paises.reset_index().sort_values(by='quantity')[:1]

  country  quantity
8     USA      7402